### ISSUE TITLE
fastify-vite_hydrate.js does not provide an export named 'hydrate'

### ISSUE THREAD

**Issue by SuslegStyle** [terixjs/fastify-vite#14]
Hi guys,

I tried to use fastify-vite on my application based on your example app.
I face the issue when run `npm run build` and `npm run dev` commands.
In browser console I see error

`Uncaught SyntaxError: The requested module '/node_modules/.vite/fastify-vite_hydrate.js?v=8f84e2b7' does not provide an export named 'hydrate'`

But my entry/client.js file is the following

`
import { createApp } from '../main';
import { hydrate } from 'fastify-vite/hydrate';
const { app, router } = createApp();

hydrate(app);

// Wait until router is ready before mounting to ensure hydration match
router.isReady().then(() => app.mount('#app'));
`

Looks like something goes wrong under the hood.

If I run `npm run build` and `npm run serve` then I don't see the issue, but I can't debug the application.

**Comment by galvez** [comment]
This is already fixed in our `dev` branch — I will _finally_ push a new release out this weekend. 

Will update here when I do.

**Comment by SuslegStyle** [comment]
Thank you, so much! 
Looking forward for the release

**Comment by galvez** [comment]
@SuslegStyle heads up, `fastify-vite@2.2.0-beta.1` and `fastify-vite-vue@2.2.0-beta.1` are available on npm now.

Refer to [terixjs/framework`](https://github.com/terixjs/framework) for a working boilerplate.

**Comment by SuslegStyle** [comment]
Thanks a lot! It works like a charm!
