### ISSUE TITLE
Error on basic install from docs

### ISSUE THREAD

**Issue by jwing8** [terixjs/fastify-vite#37]
This is my first experience with fastify-vite and I'm attempting to follow the Vue quickstart instructions, however I get the following error when running node app.mjs

- C:\Users\Jeff\fite\node_modules\vite\dist\node\chunks\dep-85dbaaa7.js:66477
        throw new Error(`failed to load module for ssr: ${url}`);

**Comment by galvez** [comment]
Hey @jwing8 — can you share a reproduction repo?

**Comment by jwing8** [comment]
I fully expect this is user error.  It seems like something to do with my version of Node and my lack of knowledge around ESM.  Please feel free to close this issue, but I would recommend making the quickstart docs more beginner-friendly as there seems to be some implied knowledge around __dirname etc.

This is an awesome project btw, thank you for creating it.  I will definitely be exploring it much more in the future.
